# Generated by Django 3.2 on 2022-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Ограничения на траты в категории'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Счет пользователя в рублях'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Количество потраченных денег'),
        ),
    ]
