# Generated by Django 3.2 on 2022-05-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220521_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Откуда были получены деньги')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Количество полученныъ денег')),
                ('datetime_created', models.DateTimeField(auto_now=True, verbose_name='Время получения денег')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category', verbose_name='Категория доходов')),
            ],
        ),
    ]
